### ISSUE TITLE
Use Kubernetes Secrets instead of ConfigMaps for storing private keys/mnemonic?

### ISSUE THREAD

**Issue by Kuzirashi** [axonweb3/axon-devops#121]
What do you guys think of storing private keys/mnemonics in Secrets instead of CongigMaps? In Kubernetes it says that ConfigMaps should be used for non-confidential storage:

> Caution: ConfigMap does not provide secrecy or encryption. If the data you want to store are confidential, use a [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) rather than a ConfigMap, or use additional (third party) tools to keep your data private.
>
> Source: https://kubernetes.io/docs/concepts/configuration/configmap/

**Comment by liya2017** [comment]
Hi, this branch is the sample of storing private key in secrets. https://github.com/axonweb3/axon-devops/tree/move-key-to-secret

please try it feel free  and let me know if you still have other issues. Thanks

**Comment by liya2017** [comment]
@Kuzirashi hi , could we close this issue?
