### ISSUE TITLE
How to generate private key for Axon node toml configuration?

### ISSUE THREAD

**Issue by Kuzirashi** [axonweb3/axon-devops#122]
Hey guys, I've tried to change private key of a node but it complains that it has to be BLS private key.

Is there anything specific regarding how to generate private key for Axon node that is used in node_1.toml, node_2.toml etc.?

**Comment by liya2017** [comment]
Hi, sorry for the late reply. 
We have completed development for your needs, it can be used once the reviewer approve it. 
Will let you know when it done.

**Comment by Kuzirashi** [comment]
Hey @liya2017, is there an update regarding generating BLS keys?

**Comment by liya2017** [comment]
Hi @Kuzirashi ,sorry for the late responses.  
Yes we have some [steps](https://docs.axonweb3.io/getting-started/for-dapp-devs/zero_to_axon_with_axon_cli#managing-axon-nodes)  for it, please feel free to try.
